### PR TITLE
Limit iterations when reordering comments

### PR DESCRIPTION
**Pull request by scpeters**
During the "Reordering comments" phase, the script can get stuck
in an infinite loop if there is missing data, which I have observed
when a comment page fails to download with a 404 from the bitbucket
REST API.
Currently the loop runs as long as `len(done_idxs) < len(comments)`,
so this change checks for the value of `len(done_idxs)` to stop
changing and runs 5 extra iterations before continuing.

I noticed this with the following comment, which returns 404 when trying to query it through the REST API:

* https://bitbucket.org/osrf/sdf_tutorials/pull-requests/13/replace-joint-frame-references-with-jc-and/activity#comment-100210566
* https://api.bitbucket.org/2.0/repositories/osrf/sdf_tutorials/pullrequests/13/comments/100210566

I tried to edit the reply to that comment, but I'm not sure the REST API data gets updated after comment edits.

### CODE REVIEW

**Comment by philipstarkey** [comment]
So I'm a little confused....I didn't think that code actually touched the `pullrequests/<num>/comments/<id>` files...isn't it just iterating over the `pullrequests/<num>/comments` (page 1, 2, etc) files?

Oh, I see. The data for that comment is also just missing from the `pullrequests/<num>/comments` files too (see https://api.bitbucket.org/2.0/repositories/osrf/sdf_tutorials/pullrequests/13/comments/?pagelen=100 ). The child comment is there, but not the parent.

I think I've seen everything with the BitBucket API and then we discover it can just silently drop content....wow.

Ok, so I'm happy to do something like this to work around it, but I think it needs more work. In it's current state I'm reasonably certain it's going to drop the child comments when it writes out the file? It should have printed a warning in that case...did you get one?

Also do these show up in the BitBucket archive? They're only on the activity page in your links above and I'm not currently rendering that in my archive...

**Comment by scpeters** [comment]
> In it's current state I'm reasonably certain it's going to drop the child comments when it writes out the file? It should have printed a warning in that case...did you get one?

Yes, I remember seeing an error message, though I don't have that console output saved. I believe it was the following error:

* https://github.com/philipstarkey/bitbucket-hg-exporter/blob/master/bitbucket_hg_exporter/__main__.py#L989-L990

Looking at the exported GitHub pages, neither the missing parent nor its child comment are rendered on the pull request page:

* https://scpeters-test.github.io/gh-pages_sdf_tutorials_fast_export/#!/osrf/sdf_tutorials/pull-requests/13/page/1#comment-99874407

I had assumed the error message mentioned above was caused by the missing parent comment, but now that you suggest it, perhaps it is the child comment that has been successfully downloaded but not rendered anywhere. Yeah, it would be nice to figure out how to render it somehow,  but I'm not yet familiar enough with this code to make a big change like that on my own. I'd be happy to test any suggestions you have.

**Comment by philipstarkey** [comment]
Ok, I've started fixing it but it's going to take a few days. I need to insert a dummy comment the right location with the right id, and that means I need to accommodate potentially creating a new page file with the appropriate structure (and updating the details in what was previously the last page) to handle the case where the number of comments increases over a page boundary.

I'm almost looking forward to Atlassian deleting all of our data now so that I don't have to deal with the abysmal API anymore!

**Comment by philipstarkey** [comment]
Sorry it took me a while to get to this, I've had other things on my plate. But I had need to use my code again today, so needed to get it in a working state again!

If you are still interested in testing, the fix should be in df8c6e204

**Comment by scpeters** [comment]
> If you are still interested in testing, the fix should be in df8c6e2

Ok, I'll give it a try

**Comment by scpeters** [comment]
I just tested using https://github.com/scpeters/bitbucket-hg-exporter/commit/0edbe393470d8b017debaf4fcf4eb45034c9ed31 (branch [scpeters_debug_pr36alt](https://github.com/scpeters/bitbucket-hg-exporter/commits/scpeters_debug_pr36alt), which includes df8c6e204e08f896ccee0f9942f5aa36d5d9c553) with the same sdf_tutorials example mentioned above and got the following exception when re-ordering comments:

~~~
Reordering comments...
Traceback (most recent call last):
  File "/data_fast/scpeters/ws/bb_venv/bin/bitbucket-hg-exporter", line 11, in <module>
    load_entry_point('bitbucket-hg-exporter==0.6.2', 'console_scripts', 'bitbucket-hg-exporter')()
  File "/data_fast/scpeters/ws/bb_venv/lib/python3.7/site-packages/bitbucket_hg_exporter/__main__.py", line 2478, in main
    project = MigrationProject()
  File "/data_fast/scpeters/ws/bb_venv/lib/python3.7/site-packages/bitbucket_hg_exporter/__main__.py", line 280, in __init__
    self.__load_project(**kwargs)
  File "/data_fast/scpeters/ws/bb_venv/lib/python3.7/site-packages/bitbucket_hg_exporter/__main__.py", line 311, in __load_project
    self.__confirm_project_settings(load=True)
  File "/data_fast/scpeters/ws/bb_venv/lib/python3.7/site-packages/bitbucket_hg_exporter/__main__.py", line 969, in __confirm_project_settings
    "href": child_comment['links']['self']['href'].replace(child_comment['id'], parent_idx)
TypeError: replace() argument 1 must be str, not int
~~~

**Comment by philipstarkey** [comment]
Yep, that piece of code was buggy for a number of reasons! Would you mind trying again with 6b4f9c9a?

**Comment by scpeters** [comment]
Yeah, it looks much better with 6b4f9c9

* https://osrf-migration.github.io/sdf_tutorials-gh-pages/#!/osrf/sdf_tutorials/pull-requests/13/page/1#comment-100210566

Thanks!

**Pull request closed without merging**
