### PR TITLE
Fix #24

### LINKED ISSUE #24: SyntaxError in __main__.py
There is a syntax error here (missing comma): https://github.com/philipstarkey/bitbucket-hg-exporter/blob/c191d4a2dcf48333144ae47f89586758acd4c5dc/bitbucket_hg_exporter/__main__.py#L691

### PR DESCRIPTION
**Pull request by levitsky**
Sorry for extra whitespace edits, those are automatic. This change simply adds the missing commas.

### CODE REVIEW

**Comment by philipstarkey** [comment]
Thanks!

Do you think you could not include the many white space changes though? It makes it hard to see the important changes made (I'm not opposed to white space changes, but probably the whole thing should just be run through 'black' as a separate PR)

As a further aside, I recommend using the tip of this repository with caution. It's not tested at all yet (hence the syntax errors). It's much safer to use one of the tagged versions or install via pip (which should only use the tagged versions)

**Comment by levitsky** [comment]
You can click "hide whitespace changes" on the "Files changed" tab to review the meaningful changes:
image
I can create a separate PR without the whitespace edits though.

**Comment by scpeters** [comment]
I've fixed the commas without any whitespace changes as well as a few other syntax errors I noticed in #28

**Comment by levitsky** [comment]
Ah okay, this can be closed then.

**Pull request closed without merging**
